"""Additional seed data — 40+ more recipes for production."""
import asyncio
import uuid
from datetime import datetime, timedelta
import random

from src.db.engine import engine, async_session
from src.db.tables import Base, RecipeRow


EXTRA_RECIPES = [
    {
        "title": "Greek Chicken Bowl with Tzatziki",
        "description": "Mediterranean-inspired protein bowl that's ready in 20 minutes. Perfectly seasoned chicken with fresh veggies and creamy tzatziki.",
        "creator_username": "cleanfoodcrush",
        "creator_display_name": "Rachel | Clean Food Crush",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@cleanfoodcrush",
        "creator_avatar_url": None,
        "creator_follower_count": 560000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example1",
        "thumbnail_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
        "ingredients": [
            {"name": "chicken breast", "quantity": "8 oz", "category": "protein"},
            {"name": "Greek yogurt", "quantity": "1/2 cup", "category": "dairy"},
            {"name": "cucumber", "quantity": "1 medium, diced", "category": "produce"},
            {"name": "cherry tomatoes", "quantity": "1 cup, halved", "category": "produce"},
            {"name": "red onion", "quantity": "1/4, sliced", "category": "produce"},
            {"name": "lemon juice", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "oregano", "quantity": "1 tsp", "category": "spice"},
        ],
        "steps": [
            "Season chicken with oregano, salt, pepper, and lemon juice.",
            "Grill or pan-sear chicken over medium-high heat, 6-7 min per side.",
            "Mix yogurt with diced cucumber, garlic, lemon juice, and dill for tzatziki.",
            "Slice chicken and arrange over greens with tomatoes and red onion.",
            "Drizzle with tzatziki and serve.",
        ],
        "tags": ["high-protein", "mediterranean", "meal-prep", "quick", "low-carb"],
        "calories": 385, "protein_g": 52, "carbs_g": 12, "fat_g": 14, "fiber_g": 3, "sugar_g": 6,
        "servings": 1, "cook_time_minutes": 20, "difficulty": "easy",
        "views": 890000, "likes": 67000, "comments": 2300, "shares": 12000,
    },
    {
        "title": "5-Minute Tuna Salad Protein Wrap",
        "description": "The easiest high-protein lunch ever. No cooking required, meal prep friendly, and absolutely delicious.",
        "creator_username": "fitmencook",
        "creator_display_name": "Kevin | FitMenCook",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@fitmencook",
        "creator_avatar_url": None,
        "creator_follower_count": 2100000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example2",
        "thumbnail_url": "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600",
        "ingredients": [
            {"name": "canned tuna in water", "quantity": "2 cans (5oz each)", "category": "protein"},
            {"name": "avocado", "quantity": "1/2 medium", "category": "produce"},
            {"name": "whole wheat tortilla", "quantity": "1 large", "category": "grain"},
            {"name": "celery", "quantity": "1 stalk, diced", "category": "produce"},
            {"name": "Dijon mustard", "quantity": "1 tsp", "category": "condiment"},
            {"name": "lemon juice", "quantity": "1 tbsp", "category": "pantry"},
        ],
        "steps": [
            "Drain tuna and place in a bowl.",
            "Mash avocado and mix with tuna, celery, mustard, and lemon juice.",
            "Season with salt, pepper, and optional hot sauce.",
            "Spread mixture on tortilla, add lettuce if desired, and wrap tightly.",
            "Cut in half and serve immediately or wrap in foil for later.",
        ],
        "tags": ["high-protein", "no-cook", "quick", "meal-prep", "lunch"],
        "calories": 420, "protein_g": 55, "carbs_g": 28, "fat_g": 12, "fiber_g": 7, "sugar_g": 2,
        "servings": 1, "cook_time_minutes": 5, "difficulty": "easy",
        "views": 1500000, "likes": 98000, "comments": 4100, "shares": 25000,
    },
    {
        "title": "Protein Banana Pancakes (3 Ingredients)",
        "description": "Fluffy, golden pancakes with 40g protein. Perfect weekend breakfast that's actually healthy.",
        "creator_username": "healthygirlkitchen",
        "creator_display_name": "Danielle | Healthy Girl Kitchen",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/healthygirlkitchen",
        "creator_avatar_url": None,
        "creator_follower_count": 45000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/fitmeals/comments/example3",
        "thumbnail_url": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600",
        "ingredients": [
            {"name": "ripe banana", "quantity": "1 large", "category": "produce"},
            {"name": "egg whites", "quantity": "4 large", "category": "protein"},
            {"name": "vanilla protein powder", "quantity": "1 scoop (30g)", "category": "supplement"},
        ],
        "steps": [
            "Mash banana in a bowl until smooth.",
            "Whisk in egg whites and protein powder until combined.",
            "Heat a non-stick pan over medium-low heat with light cooking spray.",
            "Pour 1/4 cup batter per pancake, cook 2-3 min until bubbles form.",
            "Flip and cook 1-2 more minutes until golden.",
            "Top with fresh berries and a drizzle of sugar-free maple syrup.",
        ],
        "tags": ["high-protein", "breakfast", "3-ingredients", "quick", "low-fat"],
        "calories": 295, "protein_g": 40, "carbs_g": 32, "fat_g": 3, "fiber_g": 3, "sugar_g": 18,
        "servings": 1, "cook_time_minutes": 10, "difficulty": "easy",
        "views": 670000, "likes": 52000, "comments": 1800, "shares": 15000,
    },
    {
        "title": "Turkey Taco Lettuce Wraps",
        "description": "All the taco flavor with a fraction of the carbs. Ground turkey seasoned to perfection in crisp lettuce cups.",
        "creator_username": "macrofriendly",
        "creator_display_name": "Jake | Macro Friendly",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/macrofriendly",
        "creator_avatar_url": None,
        "creator_follower_count": 38000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/mealprep/comments/example4",
        "thumbnail_url": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600",
        "ingredients": [
            {"name": "lean ground turkey (99%)", "quantity": "1 lb", "category": "protein"},
            {"name": "butter lettuce heads", "quantity": "2", "category": "produce"},
            {"name": "taco seasoning", "quantity": "2 tbsp", "category": "spice"},
            {"name": "black beans", "quantity": "1/2 cup, drained", "category": "pantry"},
            {"name": "salsa", "quantity": "1/4 cup", "category": "condiment"},
            {"name": "Greek yogurt (as sour cream)", "quantity": "2 tbsp", "category": "dairy"},
        ],
        "steps": [
            "Brown ground turkey in a skillet over medium-high heat, breaking into crumbles.",
            "Add taco seasoning and 1/4 cup water, simmer 3-4 minutes.",
            "Stir in black beans and heat through.",
            "Separate lettuce leaves to form cups.",
            "Fill each cup with turkey mixture, top with salsa and yogurt.",
        ],
        "tags": ["high-protein", "low-carb", "keto-friendly", "quick", "dinner"],
        "calories": 310, "protein_g": 46, "carbs_g": 16, "fat_g": 8, "fiber_g": 5, "sugar_g": 4,
        "servings": 2, "cook_time_minutes": 15, "difficulty": "easy",
        "views": 420000, "likes": 34000, "comments": 1200, "shares": 8900,
    },
    {
        "title": "Shrimp Stir-Fry with Cauliflower Rice",
        "description": "Restaurant-quality stir-fry at home for under 300 calories. The garlic ginger sauce is *chef's kiss*.",
        "creator_username": "seriouslyfit",
        "creator_display_name": "Maya | Seriously Fit Eats",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@seriouslyfit",
        "creator_avatar_url": None,
        "creator_follower_count": 780000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example5",
        "thumbnail_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600",
        "ingredients": [
            {"name": "shrimp, peeled", "quantity": "1 lb", "category": "protein"},
            {"name": "riced cauliflower", "quantity": "2 cups", "category": "produce"},
            {"name": "broccoli florets", "quantity": "1 cup", "category": "produce"},
            {"name": "soy sauce (low sodium)", "quantity": "2 tbsp", "category": "condiment"},
            {"name": "garlic", "quantity": "3 cloves, minced", "category": "produce"},
            {"name": "fresh ginger", "quantity": "1 tsp, grated", "category": "produce"},
            {"name": "sesame oil", "quantity": "1 tsp", "category": "pantry"},
        ],
        "steps": [
            "Heat sesame oil in a large wok or skillet over high heat.",
            "Add shrimp in a single layer, sear 2 min per side. Remove.",
            "Add garlic, ginger, and broccoli. Stir-fry 3 minutes.",
            "Add cauliflower rice and soy sauce. Cook 2-3 minutes.",
            "Return shrimp to pan, toss everything together.",
            "Serve with optional sriracha and sliced green onions.",
        ],
        "tags": ["high-protein", "low-carb", "asian", "quick", "seafood"],
        "calories": 280, "protein_g": 42, "carbs_g": 14, "fat_g": 8, "fiber_g": 4, "sugar_g": 4,
        "servings": 2, "cook_time_minutes": 15, "difficulty": "easy",
        "views": 1200000, "likes": 89000, "comments": 3200, "shares": 20000,
    },
    {
        "title": "Baked Salmon with Lemon Dill",
        "description": "Perfectly flaky salmon every time. High in omega-3s and protein, ready in 20 minutes flat.",
        "creator_username": "preppykitchen",
        "creator_display_name": "John | Preppy Kitchen",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@preppykitchen",
        "creator_avatar_url": None,
        "creator_follower_count": 4200000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example6",
        "thumbnail_url": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600",
        "ingredients": [
            {"name": "salmon fillets", "quantity": "2 (6oz each)", "category": "protein"},
            {"name": "lemon", "quantity": "1, sliced", "category": "produce"},
            {"name": "fresh dill", "quantity": "2 tbsp, chopped", "category": "produce"},
            {"name": "olive oil", "quantity": "1 tbsp", "category": "pantry"},
            {"name": "garlic powder", "quantity": "1/2 tsp", "category": "spice"},
            {"name": "asparagus", "quantity": "1 bunch, trimmed", "category": "produce"},
        ],
        "steps": [
            "Preheat oven to 400°F (200°C).",
            "Place salmon and asparagus on a lined baking sheet.",
            "Drizzle with olive oil, season with garlic powder, salt, and pepper.",
            "Top salmon with lemon slices and fresh dill.",
            "Bake 12-15 minutes until salmon flakes easily.",
            "Serve immediately with lemon wedges.",
        ],
        "tags": ["high-protein", "omega-3", "dinner", "quick", "sheet-pan"],
        "calories": 365, "protein_g": 44, "carbs_g": 8, "fat_g": 18, "fiber_g": 3, "sugar_g": 2,
        "servings": 2, "cook_time_minutes": 20, "difficulty": "easy",
        "views": 3400000, "likes": 245000, "comments": 8900, "shares": 56000,
    },
    {
        "title": "Protein-Packed Smoothie Bowl",
        "description": "Thick, creamy, and Instagram-worthy. 45g protein and tastes like a milkshake.",
        "creator_username": "smoothieking_homemade",
        "creator_display_name": "Lisa | Smoothie Queen",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/smoothieking_homemade",
        "creator_avatar_url": None,
        "creator_follower_count": 22000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/fitmeals/comments/example7",
        "thumbnail_url": "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600",
        "ingredients": [
            {"name": "frozen mixed berries", "quantity": "1 cup", "category": "produce"},
            {"name": "vanilla protein powder", "quantity": "1.5 scoops", "category": "supplement"},
            {"name": "frozen banana", "quantity": "1/2", "category": "produce"},
            {"name": "Greek yogurt", "quantity": "1/2 cup", "category": "dairy"},
            {"name": "almond milk", "quantity": "1/4 cup", "category": "dairy"},
            {"name": "granola", "quantity": "2 tbsp", "category": "pantry"},
        ],
        "steps": [
            "Blend berries, protein powder, banana, yogurt, and almond milk until thick.",
            "Use minimal liquid for a thick, spoonable consistency.",
            "Pour into a bowl.",
            "Top with granola, sliced banana, and extra berries.",
            "Drizzle with honey or nut butter if desired.",
        ],
        "tags": ["high-protein", "breakfast", "smoothie", "quick", "vegetarian"],
        "calories": 380, "protein_g": 45, "carbs_g": 42, "fat_g": 6, "fiber_g": 7, "sugar_g": 24,
        "servings": 1, "cook_time_minutes": 5, "difficulty": "easy",
        "views": 560000, "likes": 41000, "comments": 1500, "shares": 11000,
    },
    {
        "title": "Chipotle-Style Chicken Burrito Bowl",
        "description": "Restaurant copycat that's actually healthy. All the flavor of Chipotle with half the calories.",
        "creator_username": "joshuaweissman",
        "creator_display_name": "Joshua Weissman",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@joshuaweissman",
        "creator_avatar_url": None,
        "creator_follower_count": 9800000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example8",
        "thumbnail_url": "https://images.unsplash.com/photo-1543339308-d595c48b1fc7?w=600",
        "ingredients": [
            {"name": "chicken breast", "quantity": "8 oz", "category": "protein"},
            {"name": "brown rice", "quantity": "1/2 cup cooked", "category": "grain"},
            {"name": "black beans", "quantity": "1/2 cup", "category": "pantry"},
            {"name": "corn", "quantity": "1/4 cup", "category": "produce"},
            {"name": "salsa", "quantity": "1/4 cup", "category": "condiment"},
            {"name": "lime juice", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "cilantro", "quantity": "2 tbsp, chopped", "category": "produce"},
            {"name": "chipotle in adobo", "quantity": "1 pepper, minced", "category": "spice"},
        ],
        "steps": [
            "Marinate chicken in chipotle, lime juice, and cumin for at least 15 minutes.",
            "Grill or pan-sear chicken until cooked through, 6-7 min per side.",
            "Cook rice and stir in lime juice and cilantro.",
            "Warm black beans with cumin and garlic.",
            "Slice chicken and assemble bowl: rice, beans, corn, chicken, salsa.",
            "Top with Greek yogurt instead of sour cream for extra protein.",
        ],
        "tags": ["high-protein", "meal-prep", "mexican", "dinner", "copycat"],
        "calories": 450, "protein_g": 50, "carbs_g": 42, "fat_g": 10, "fiber_g": 9, "sugar_g": 5,
        "servings": 1, "cook_time_minutes": 25, "difficulty": "medium",
        "views": 4500000, "likes": 312000, "comments": 12000, "shares": 78000,
    },
    {
        "title": "Cottage Cheese Protein Waffles",
        "description": "Crispy outside, fluffy inside, 35g protein per waffle. The cottage cheese hack that broke the internet.",
        "creator_username": "themodernnesting",
        "creator_display_name": "Sarah | Modern Nesting",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/themodernnesting",
        "creator_avatar_url": None,
        "creator_follower_count": 15000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/healthyrecipes/comments/example9",
        "thumbnail_url": "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600",
        "ingredients": [
            {"name": "cottage cheese", "quantity": "1 cup", "category": "dairy"},
            {"name": "eggs", "quantity": "2 large", "category": "protein"},
            {"name": "oats", "quantity": "1/2 cup", "category": "grain"},
            {"name": "vanilla extract", "quantity": "1 tsp", "category": "pantry"},
            {"name": "baking powder", "quantity": "1/2 tsp", "category": "pantry"},
        ],
        "steps": [
            "Blend all ingredients in a blender until smooth.",
            "Let batter rest 2 minutes while waffle iron heats.",
            "Pour batter into greased waffle iron.",
            "Cook until golden and crispy, about 4-5 minutes.",
            "Top with fresh berries and a light drizzle of maple syrup.",
        ],
        "tags": ["high-protein", "breakfast", "cottage-cheese", "viral", "quick"],
        "calories": 340, "protein_g": 35, "carbs_g": 28, "fat_g": 10, "fiber_g": 3, "sugar_g": 5,
        "servings": 1, "cook_time_minutes": 10, "difficulty": "easy",
        "views": 2100000, "likes": 178000, "comments": 5600, "shares": 34000,
    },
    {
        "title": "Korean Beef Rice Bowl (Bulgogi Style)",
        "description": "Sweet, savory, umami-packed Korean beef bowl that's meal prep gold. 48g protein per serving.",
        "creator_username": "mealprepsunday",
        "creator_display_name": "MealPrep Sunday",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/mealprepsunday",
        "creator_avatar_url": None,
        "creator_follower_count": 890000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/MealPrepSunday/comments/example10",
        "thumbnail_url": "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600",
        "ingredients": [
            {"name": "lean ground beef (93%)", "quantity": "1 lb", "category": "protein"},
            {"name": "soy sauce", "quantity": "3 tbsp", "category": "condiment"},
            {"name": "brown sugar", "quantity": "1 tbsp", "category": "pantry"},
            {"name": "sesame oil", "quantity": "1 tsp", "category": "pantry"},
            {"name": "garlic", "quantity": "3 cloves, minced", "category": "produce"},
            {"name": "ginger", "quantity": "1 tsp, grated", "category": "produce"},
            {"name": "jasmine rice", "quantity": "1 cup cooked", "category": "grain"},
            {"name": "green onions", "quantity": "3, sliced", "category": "produce"},
        ],
        "steps": [
            "Brown ground beef in a large skillet, breaking into small pieces.",
            "Drain excess fat.",
            "Mix soy sauce, brown sugar, sesame oil, garlic, and ginger.",
            "Pour sauce over beef, simmer 3-4 minutes until glazed.",
            "Serve over jasmine rice topped with green onions and sesame seeds.",
        ],
        "tags": ["high-protein", "korean", "meal-prep", "dinner", "asian"],
        "calories": 430, "protein_g": 48, "carbs_g": 35, "fat_g": 12, "fiber_g": 2, "sugar_g": 6,
        "servings": 2, "cook_time_minutes": 15, "difficulty": "easy",
        "views": 780000, "likes": 62000, "comments": 2100, "shares": 15000,
    },
    {
        "title": "Protein Chia Pudding (Overnight)",
        "description": "Set it and forget it. Wake up to a creamy, protein-rich breakfast with zero morning effort.",
        "creator_username": "simplyprotein",
        "creator_display_name": "Simply Protein",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/simplyprotein",
        "creator_avatar_url": None,
        "creator_follower_count": 12000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/EatCheapAndHealthy/comments/example11",
        "thumbnail_url": "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600",
        "ingredients": [
            {"name": "chia seeds", "quantity": "3 tbsp", "category": "pantry"},
            {"name": "protein powder", "quantity": "1 scoop", "category": "supplement"},
            {"name": "almond milk", "quantity": "1 cup", "category": "dairy"},
            {"name": "maple syrup", "quantity": "1 tsp", "category": "pantry"},
            {"name": "frozen berries", "quantity": "1/4 cup", "category": "produce"},
        ],
        "steps": [
            "Mix chia seeds, protein powder, and almond milk in a jar.",
            "Stir well to prevent clumps, then stir again after 5 minutes.",
            "Add maple syrup, cover, and refrigerate overnight (at least 4 hours).",
            "In the morning, stir and top with berries, nuts, or coconut flakes.",
        ],
        "tags": ["high-protein", "breakfast", "no-cook", "meal-prep", "overnight"],
        "calories": 285, "protein_g": 32, "carbs_g": 24, "fat_g": 10, "fiber_g": 12, "sugar_g": 8,
        "servings": 1, "cook_time_minutes": 5, "difficulty": "easy",
        "views": 340000, "likes": 28000, "comments": 900, "shares": 7600,
    },
    {
        "title": "Stuffed Bell Peppers (High Protein)",
        "description": "Colorful, satisfying, and perfect for meal prep. Each pepper packs 38g protein.",
        "creator_username": "fitfoodiefinds",
        "creator_display_name": "Fit Foodie Finds",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@fitfoodiefinds",
        "creator_avatar_url": None,
        "creator_follower_count": 340000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example12",
        "thumbnail_url": "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=600",
        "ingredients": [
            {"name": "bell peppers", "quantity": "4 large", "category": "produce"},
            {"name": "lean ground turkey", "quantity": "1 lb", "category": "protein"},
            {"name": "brown rice", "quantity": "1 cup cooked", "category": "grain"},
            {"name": "marinara sauce", "quantity": "1 cup", "category": "condiment"},
            {"name": "mozzarella cheese", "quantity": "1/2 cup, shredded", "category": "dairy"},
            {"name": "Italian seasoning", "quantity": "1 tbsp", "category": "spice"},
        ],
        "steps": [
            "Preheat oven to 375°F. Cut tops off peppers and remove seeds.",
            "Brown turkey in a skillet, season with Italian seasoning.",
            "Mix cooked turkey with rice and marinara sauce.",
            "Stuff peppers with the mixture and place in a baking dish.",
            "Top with mozzarella cheese.",
            "Cover with foil and bake 25 min, then uncover and bake 10 more.",
        ],
        "tags": ["high-protein", "meal-prep", "dinner", "stuffed-peppers", "italian"],
        "calories": 350, "protein_g": 38, "carbs_g": 28, "fat_g": 10, "fiber_g": 5, "sugar_g": 8,
        "servings": 4, "cook_time_minutes": 40, "difficulty": "medium",
        "views": 920000, "likes": 71000, "comments": 2800, "shares": 18000,
    },
    {
        "title": "Protein Energy Balls (No Bake)",
        "description": "The perfect pre-workout or afternoon snack. 12g protein per ball, takes 10 minutes to make a batch of 12.",
        "creator_username": "snackgirl",
        "creator_display_name": "Snack Girl",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/snackgirl",
        "creator_avatar_url": None,
        "creator_follower_count": 8500,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/fitmeals/comments/example13",
        "thumbnail_url": "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600",
        "ingredients": [
            {"name": "oats", "quantity": "1 cup", "category": "grain"},
            {"name": "peanut butter", "quantity": "1/2 cup", "category": "pantry"},
            {"name": "chocolate protein powder", "quantity": "2 scoops", "category": "supplement"},
            {"name": "honey", "quantity": "3 tbsp", "category": "pantry"},
            {"name": "mini chocolate chips", "quantity": "2 tbsp", "category": "pantry"},
        ],
        "steps": [
            "Mix all ingredients in a large bowl until well combined.",
            "If too dry, add 1 tbsp milk. If too wet, add more oats.",
            "Refrigerate 15 minutes to firm up.",
            "Roll into 12 balls (about 1.5 inch each).",
            "Store in fridge for up to 1 week or freeze for 3 months.",
        ],
        "tags": ["high-protein", "snack", "no-bake", "meal-prep", "quick"],
        "calories": 145, "protein_g": 12, "carbs_g": 14, "fat_g": 6, "fiber_g": 2, "sugar_g": 7,
        "servings": 12, "cook_time_minutes": 10, "difficulty": "easy",
        "views": 450000, "likes": 38000, "comments": 1100, "shares": 9500,
    },
    {
        "title": "Lemon Herb Grilled Chicken Thighs",
        "description": "Juicy, flavorful chicken thighs that work for any meal. The marinade is the secret weapon.",
        "creator_username": "budgetbytes",
        "creator_display_name": "Beth | Budget Bytes",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@budgetbytes",
        "creator_avatar_url": None,
        "creator_follower_count": 620000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example14",
        "thumbnail_url": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600",
        "ingredients": [
            {"name": "boneless skinless chicken thighs", "quantity": "1.5 lbs", "category": "protein"},
            {"name": "lemon juice", "quantity": "3 tbsp", "category": "pantry"},
            {"name": "olive oil", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "garlic", "quantity": "4 cloves, minced", "category": "produce"},
            {"name": "dried oregano", "quantity": "1 tsp", "category": "spice"},
            {"name": "dried thyme", "quantity": "1 tsp", "category": "spice"},
            {"name": "paprika", "quantity": "1/2 tsp", "category": "spice"},
        ],
        "steps": [
            "Mix lemon juice, olive oil, garlic, and herbs for marinade.",
            "Marinate chicken at least 30 min (up to overnight).",
            "Preheat grill or grill pan to medium-high.",
            "Grill 5-6 minutes per side until internal temp reaches 165°F.",
            "Rest 5 minutes before slicing.",
            "Serve with roasted vegetables or in meal prep containers.",
        ],
        "tags": ["high-protein", "meal-prep", "grilled", "dinner", "low-carb"],
        "calories": 290, "protein_g": 38, "carbs_g": 3, "fat_g": 14, "fiber_g": 0, "sugar_g": 1,
        "servings": 4, "cook_time_minutes": 15, "difficulty": "easy",
        "views": 1100000, "likes": 82000, "comments": 3100, "shares": 22000,
    },
    {
        "title": "Zucchini Noodle Pad Thai",
        "description": "All the pad thai flavor without the carb crash. Crunchy zoodles with peanut sauce perfection.",
        "creator_username": "plantyou",
        "creator_display_name": "Carleigh | PlantYou",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@plantyou",
        "creator_avatar_url": None,
        "creator_follower_count": 890000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example15",
        "thumbnail_url": "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600",
        "ingredients": [
            {"name": "zucchini", "quantity": "3 medium, spiralized", "category": "produce"},
            {"name": "shrimp or chicken", "quantity": "8 oz", "category": "protein"},
            {"name": "peanut butter", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "soy sauce", "quantity": "2 tbsp", "category": "condiment"},
            {"name": "lime juice", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "sriracha", "quantity": "1 tsp", "category": "condiment"},
            {"name": "peanuts", "quantity": "2 tbsp, crushed", "category": "pantry"},
            {"name": "bean sprouts", "quantity": "1/2 cup", "category": "produce"},
        ],
        "steps": [
            "Spiralize zucchini and pat dry with paper towels.",
            "Cook protein of choice, set aside.",
            "Whisk peanut butter, soy sauce, lime juice, and sriracha for sauce.",
            "Quickly sauté zoodles 1-2 minutes (don't overcook — they'll get watery).",
            "Toss with sauce and protein.",
            "Top with crushed peanuts, bean sprouts, and lime wedges.",
        ],
        "tags": ["low-carb", "high-protein", "asian", "zoodles", "quick"],
        "calories": 320, "protein_g": 36, "carbs_g": 18, "fat_g": 14, "fiber_g": 5, "sugar_g": 8,
        "servings": 2, "cook_time_minutes": 15, "difficulty": "easy",
        "views": 670000, "likes": 51000, "comments": 1800, "shares": 13000,
    },
    {
        "title": "One-Pan Mediterranean Chicken",
        "description": "Everything cooks in one pan — chicken, sun-dried tomatoes, olives, and spinach in a creamy sauce.",
        "creator_username": "halfbakedharvest",
        "creator_display_name": "Tieghan | Half Baked Harvest",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@halfbakedharvest",
        "creator_avatar_url": None,
        "creator_follower_count": 1500000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example16",
        "thumbnail_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600",
        "ingredients": [
            {"name": "chicken breast", "quantity": "1 lb, sliced", "category": "protein"},
            {"name": "sun-dried tomatoes", "quantity": "1/4 cup", "category": "pantry"},
            {"name": "kalamata olives", "quantity": "1/4 cup", "category": "pantry"},
            {"name": "fresh spinach", "quantity": "2 cups", "category": "produce"},
            {"name": "chicken broth", "quantity": "1/2 cup", "category": "pantry"},
            {"name": "garlic", "quantity": "3 cloves", "category": "produce"},
            {"name": "Italian seasoning", "quantity": "1 tbsp", "category": "spice"},
        ],
        "steps": [
            "Season chicken with Italian seasoning, salt, and pepper.",
            "Sear chicken in a large skillet 5-6 min per side. Remove.",
            "Sauté garlic 30 seconds, add sun-dried tomatoes and olives.",
            "Pour in chicken broth, scrape up browned bits.",
            "Add spinach and stir until wilted.",
            "Return chicken to pan, simmer 3-4 minutes to heat through.",
        ],
        "tags": ["high-protein", "mediterranean", "one-pan", "dinner", "quick"],
        "calories": 340, "protein_g": 44, "carbs_g": 10, "fat_g": 14, "fiber_g": 3, "sugar_g": 4,
        "servings": 2, "cook_time_minutes": 20, "difficulty": "easy",
        "views": 2300000, "likes": 167000, "comments": 6200, "shares": 42000,
    },
    {
        "title": "Protein Acai Bowl",
        "description": "Thick, purple, and packed with 38g protein. Better than any juice bar and you control the ingredients.",
        "creator_username": "acaibowlqueen",
        "creator_display_name": "Acai Bowl Queen",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/acaibowlqueen",
        "creator_avatar_url": None,
        "creator_follower_count": 5000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/fitmeals/comments/example17",
        "thumbnail_url": "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600",
        "ingredients": [
            {"name": "frozen acai packet", "quantity": "1 (100g)", "category": "produce"},
            {"name": "frozen banana", "quantity": "1/2", "category": "produce"},
            {"name": "protein powder", "quantity": "1 scoop", "category": "supplement"},
            {"name": "almond milk", "quantity": "1/4 cup", "category": "dairy"},
            {"name": "granola", "quantity": "3 tbsp", "category": "pantry"},
            {"name": "sliced strawberries", "quantity": "1/4 cup", "category": "produce"},
        ],
        "steps": [
            "Break frozen acai packet into chunks.",
            "Blend acai, banana, protein powder, and almond milk until thick.",
            "Keep it thick — add minimal liquid. It should be spoonable.",
            "Pour into a bowl, smooth the top.",
            "Arrange toppings: granola, strawberries, coconut flakes, chia seeds.",
        ],
        "tags": ["high-protein", "breakfast", "acai", "smoothie-bowl", "viral"],
        "calories": 360, "protein_g": 38, "carbs_g": 40, "fat_g": 8, "fiber_g": 8, "sugar_g": 20,
        "servings": 1, "cook_time_minutes": 5, "difficulty": "easy",
        "views": 430000, "likes": 35000, "comments": 1200, "shares": 8900,
    },
    {
        "title": "Air Fryer Turkey Meatballs",
        "description": "Crispy on the outside, juicy inside. Perfect protein snack or add to pasta. 6g protein per meatball!",
        "creator_username": "skinnytaste",
        "creator_display_name": "Gina | Skinnytaste",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@skinnytaste",
        "creator_avatar_url": None,
        "creator_follower_count": 580000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example18",
        "thumbnail_url": "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600",
        "ingredients": [
            {"name": "ground turkey (93%)", "quantity": "1 lb", "category": "protein"},
            {"name": "panko breadcrumbs", "quantity": "1/3 cup", "category": "pantry"},
            {"name": "egg", "quantity": "1 large", "category": "protein"},
            {"name": "Parmesan", "quantity": "2 tbsp, grated", "category": "dairy"},
            {"name": "garlic", "quantity": "2 cloves, minced", "category": "produce"},
            {"name": "Italian parsley", "quantity": "2 tbsp, chopped", "category": "produce"},
        ],
        "steps": [
            "Mix all ingredients gently — don't overmix.",
            "Roll into 16 meatballs (about 1.5 inch each).",
            "Place in air fryer basket in a single layer.",
            "Air fry at 380°F for 10-12 minutes, shaking halfway.",
            "Check internal temp reaches 165°F.",
            "Serve with marinara for dipping or over zoodles.",
        ],
        "tags": ["high-protein", "air-fryer", "meal-prep", "snack", "turkey"],
        "calories": 260, "protein_g": 36, "carbs_g": 8, "fat_g": 10, "fiber_g": 0, "sugar_g": 1,
        "servings": 4, "cook_time_minutes": 12, "difficulty": "easy",
        "views": 890000, "likes": 68000, "comments": 2400, "shares": 16000,
    },
    {
        "title": "Cauliflower Fried Rice",
        "description": "100 calories per bowl instead of 400. All the fried rice flavor with a massive veggie serving.",
        "creator_username": "lowcarbrecipeideas",
        "creator_display_name": "Low Carb Recipe Ideas",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/lowcarbrecipeideas",
        "creator_avatar_url": None,
        "creator_follower_count": 67000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/ketorecipes/comments/example19",
        "thumbnail_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600",
        "ingredients": [
            {"name": "riced cauliflower", "quantity": "4 cups", "category": "produce"},
            {"name": "eggs", "quantity": "2, scrambled", "category": "protein"},
            {"name": "frozen peas and carrots", "quantity": "1/2 cup", "category": "produce"},
            {"name": "soy sauce", "quantity": "2 tbsp", "category": "condiment"},
            {"name": "sesame oil", "quantity": "1 tsp", "category": "pantry"},
            {"name": "green onions", "quantity": "3, sliced", "category": "produce"},
            {"name": "garlic", "quantity": "2 cloves, minced", "category": "produce"},
        ],
        "steps": [
            "Heat sesame oil in a large wok over high heat.",
            "Scramble eggs, push to side of pan.",
            "Add garlic and peas/carrots, stir-fry 2 minutes.",
            "Add cauliflower rice, stir-fry 3-4 minutes.",
            "Add soy sauce, toss everything together.",
            "Top with green onions and serve.",
        ],
        "tags": ["low-carb", "low-calorie", "asian", "quick", "vegetarian-option"],
        "calories": 160, "protein_g": 14, "carbs_g": 14, "fat_g": 6, "fiber_g": 5, "sugar_g": 5,
        "servings": 2, "cook_time_minutes": 12, "difficulty": "easy",
        "views": 560000, "likes": 43000, "comments": 1600, "shares": 11000,
    },
    {
        "title": "Black Bean & Sweet Potato Tacos",
        "description": "Plant-based protein powerhouse. Roasted sweet potato + seasoned black beans = taco perfection.",
        "creator_username": "pickuplimes",
        "creator_display_name": "Sadia | Pick Up Limes",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@pickuplimes",
        "creator_avatar_url": None,
        "creator_follower_count": 4100000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example20",
        "thumbnail_url": "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600",
        "ingredients": [
            {"name": "sweet potato", "quantity": "1 large, cubed", "category": "produce"},
            {"name": "black beans", "quantity": "1 can (15oz), drained", "category": "pantry"},
            {"name": "corn tortillas", "quantity": "6 small", "category": "grain"},
            {"name": "cumin", "quantity": "1 tsp", "category": "spice"},
            {"name": "smoked paprika", "quantity": "1/2 tsp", "category": "spice"},
            {"name": "avocado", "quantity": "1, sliced", "category": "produce"},
            {"name": "lime", "quantity": "1, quartered", "category": "produce"},
            {"name": "cilantro", "quantity": "fresh, for garnish", "category": "produce"},
        ],
        "steps": [
            "Preheat oven to 425°F. Toss sweet potato with oil, cumin, and paprika.",
            "Roast on a sheet pan 20-25 minutes until tender and caramelized.",
            "Warm black beans with a pinch of cumin and garlic.",
            "Char tortillas directly over a gas flame or in a dry pan.",
            "Assemble: tortilla, beans, sweet potato, avocado, cilantro.",
            "Squeeze lime over everything and enjoy!",
        ],
        "tags": ["plant-based", "vegetarian", "tacos", "dinner", "meal-prep"],
        "calories": 380, "protein_g": 16, "carbs_g": 58, "fat_g": 12, "fiber_g": 14, "sugar_g": 8,
        "servings": 2, "cook_time_minutes": 30, "difficulty": "easy",
        "views": 1800000, "likes": 132000, "comments": 4500, "shares": 28000,
    },
    {
        "title": "Chicken Sausage & Veggie Sheet Pan",
        "description": "Throw it on a pan, set a timer, done. Maximum flavor, minimum effort, maximum protein.",
        "creator_username": "realfoodwhole30",
        "creator_display_name": "Real Food Whole30",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/realfoodwhole30",
        "creator_avatar_url": None,
        "creator_follower_count": 31000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/mealprep/comments/example21",
        "thumbnail_url": "https://images.unsplash.com/photo-1606923829579-0cb981a83e2e?w=600",
        "ingredients": [
            {"name": "chicken sausage links", "quantity": "4 (pre-cooked)", "category": "protein"},
            {"name": "broccoli", "quantity": "2 cups florets", "category": "produce"},
            {"name": "bell peppers", "quantity": "2, sliced", "category": "produce"},
            {"name": "red onion", "quantity": "1, quartered", "category": "produce"},
            {"name": "olive oil", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "Italian seasoning", "quantity": "1 tbsp", "category": "spice"},
        ],
        "steps": [
            "Preheat oven to 400°F. Line a sheet pan with parchment.",
            "Slice sausage links into coins.",
            "Toss all vegetables and sausage with olive oil and seasoning.",
            "Spread in a single layer on the pan.",
            "Roast 20-25 minutes, tossing halfway through.",
            "Season with salt and pepper, serve immediately.",
        ],
        "tags": ["high-protein", "sheet-pan", "meal-prep", "easy", "dinner"],
        "calories": 310, "protein_g": 28, "carbs_g": 18, "fat_g": 14, "fiber_g": 5, "sugar_g": 8,
        "servings": 4, "cook_time_minutes": 25, "difficulty": "easy",
        "views": 380000, "likes": 29000, "comments": 900, "shares": 7200,
    },
    {
        "title": "Edamame Protein Pasta",
        "description": "44g protein from just the pasta alone! Toss with pesto and veggies for the easiest high-protein meal.",
        "creator_username": "highproteinvegan",
        "creator_display_name": "High Protein Vegan",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/highproteinvegan",
        "creator_avatar_url": None,
        "creator_follower_count": 19000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/veganfitness/comments/example22",
        "thumbnail_url": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600",
        "ingredients": [
            {"name": "edamame spaghetti", "quantity": "3 oz (dry)", "category": "grain"},
            {"name": "basil pesto", "quantity": "2 tbsp", "category": "condiment"},
            {"name": "cherry tomatoes", "quantity": "1 cup, halved", "category": "produce"},
            {"name": "baby spinach", "quantity": "1 cup", "category": "produce"},
            {"name": "Parmesan", "quantity": "1 tbsp, grated", "category": "dairy"},
        ],
        "steps": [
            "Cook edamame pasta according to package directions (usually 3-4 min).",
            "Drain and toss with pesto while hot.",
            "Add cherry tomatoes and spinach — the residual heat will wilt the spinach.",
            "Top with Parmesan and red pepper flakes.",
        ],
        "tags": ["high-protein", "pasta", "quick", "vegetarian", "easy"],
        "calories": 390, "protein_g": 44, "carbs_g": 28, "fat_g": 14, "fiber_g": 8, "sugar_g": 4,
        "servings": 1, "cook_time_minutes": 8, "difficulty": "easy",
        "views": 240000, "likes": 19000, "comments": 700, "shares": 5400,
    },
    {
        "title": "Bison Burger with Sweet Potato Fries",
        "description": "Leaner than beef, more flavorful than turkey. The ultimate healthy burger combo.",
        "creator_username": "seriouseats",
        "creator_display_name": "Serious Eats",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@seriouseats",
        "creator_avatar_url": None,
        "creator_follower_count": 1200000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example23",
        "thumbnail_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600",
        "ingredients": [
            {"name": "ground bison", "quantity": "1 lb", "category": "protein"},
            {"name": "sweet potatoes", "quantity": "2 medium, cut into fries", "category": "produce"},
            {"name": "whole wheat buns", "quantity": "4", "category": "grain"},
            {"name": "lettuce", "quantity": "4 leaves", "category": "produce"},
            {"name": "tomato", "quantity": "1, sliced", "category": "produce"},
            {"name": "avocado", "quantity": "1, sliced", "category": "produce"},
        ],
        "steps": [
            "Preheat oven to 425°F for sweet potato fries.",
            "Toss sweet potato fries with 1 tbsp olive oil, salt, and paprika.",
            "Bake 20-25 min, flipping halfway.",
            "Form bison into 4 patties, season with salt and pepper.",
            "Grill or pan-sear 4-5 min per side for medium.",
            "Assemble burgers with lettuce, tomato, and avocado.",
        ],
        "tags": ["high-protein", "burger", "dinner", "bison", "comfort-food"],
        "calories": 460, "protein_g": 38, "carbs_g": 40, "fat_g": 16, "fiber_g": 7, "sugar_g": 8,
        "servings": 4, "cook_time_minutes": 25, "difficulty": "easy",
        "views": 780000, "likes": 56000, "comments": 2100, "shares": 13000,
    },
    {
        "title": "Egg White Veggie Muffin Cups",
        "description": "Meal prep 12 at once, grab and go all week. 15g protein per muffin, zero fuss.",
        "creator_username": "mealprepmonday",
        "creator_display_name": "Meal Prep Monday",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/mealprepmonday",
        "creator_avatar_url": None,
        "creator_follower_count": 42000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/MealPrepSunday/comments/example24",
        "thumbnail_url": "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600",
        "ingredients": [
            {"name": "egg whites", "quantity": "12 large (or 1.5 cups liquid)", "category": "protein"},
            {"name": "bell peppers", "quantity": "1/2 cup, diced", "category": "produce"},
            {"name": "spinach", "quantity": "1 cup, chopped", "category": "produce"},
            {"name": "turkey bacon", "quantity": "4 slices, crumbled", "category": "protein"},
            {"name": "cheddar cheese", "quantity": "1/4 cup, shredded", "category": "dairy"},
        ],
        "steps": [
            "Preheat oven to 350°F. Grease a 12-cup muffin tin.",
            "Cook and crumble turkey bacon.",
            "Divide veggies, bacon, and cheese evenly among muffin cups.",
            "Pour egg whites over the fillings, filling each cup 3/4 full.",
            "Bake 20-22 minutes until set and slightly golden.",
            "Cool, store in fridge up to 5 days. Reheat 30 sec in microwave.",
        ],
        "tags": ["high-protein", "breakfast", "meal-prep", "grab-and-go", "low-carb"],
        "calories": 85, "protein_g": 15, "carbs_g": 2, "fat_g": 2, "fiber_g": 0, "sugar_g": 1,
        "servings": 12, "cook_time_minutes": 25, "difficulty": "easy",
        "views": 920000, "likes": 74000, "comments": 2700, "shares": 19000,
    },
    {
        "title": "Thai Peanut Chicken Salad",
        "description": "Crunchy, fresh, and loaded with flavor. The peanut dressing makes everything better.",
        "creator_username": "minimalistbaker",
        "creator_display_name": "Dana | Minimalist Baker",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@minimalistbaker",
        "creator_avatar_url": None,
        "creator_follower_count": 3400000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example25",
        "thumbnail_url": "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600",
        "ingredients": [
            {"name": "grilled chicken breast", "quantity": "8 oz, sliced", "category": "protein"},
            {"name": "mixed greens", "quantity": "4 cups", "category": "produce"},
            {"name": "shredded carrots", "quantity": "1/2 cup", "category": "produce"},
            {"name": "cucumber", "quantity": "1/2, sliced", "category": "produce"},
            {"name": "peanut butter", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "soy sauce", "quantity": "1 tbsp", "category": "condiment"},
            {"name": "rice vinegar", "quantity": "1 tbsp", "category": "pantry"},
            {"name": "lime juice", "quantity": "1 tbsp", "category": "pantry"},
            {"name": "sriracha", "quantity": "1/2 tsp", "category": "condiment"},
        ],
        "steps": [
            "Whisk peanut butter, soy sauce, rice vinegar, lime juice, and sriracha for dressing.",
            "Thin with 1-2 tbsp warm water until pourable.",
            "Arrange greens, carrots, and cucumber in a large bowl.",
            "Top with sliced grilled chicken.",
            "Drizzle with peanut dressing.",
            "Garnish with chopped peanuts, cilantro, and sesame seeds.",
        ],
        "tags": ["high-protein", "salad", "thai", "lunch", "quick"],
        "calories": 395, "protein_g": 46, "carbs_g": 16, "fat_g": 18, "fiber_g": 4, "sugar_g": 6,
        "servings": 1, "cook_time_minutes": 10, "difficulty": "easy",
        "views": 1400000, "likes": 98000, "comments": 3600, "shares": 24000,
    },
    {
        "title": "Slow Cooker Chicken Tikka Masala",
        "description": "Set it in the morning, come home to restaurant-quality tikka masala. 42g protein, incredibly creamy.",
        "creator_username": "rainbowplantlife",
        "creator_display_name": "Nisha | Rainbow Plant Life",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@rainbowplantlife",
        "creator_avatar_url": None,
        "creator_follower_count": 2800000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example26",
        "thumbnail_url": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600",
        "ingredients": [
            {"name": "chicken breast", "quantity": "1.5 lbs", "category": "protein"},
            {"name": "canned diced tomatoes", "quantity": "1 can (14oz)", "category": "pantry"},
            {"name": "coconut cream", "quantity": "1/2 cup", "category": "pantry"},
            {"name": "garam masala", "quantity": "2 tbsp", "category": "spice"},
            {"name": "turmeric", "quantity": "1 tsp", "category": "spice"},
            {"name": "garlic", "quantity": "4 cloves, minced", "category": "produce"},
            {"name": "ginger", "quantity": "1 tbsp, grated", "category": "produce"},
            {"name": "basmati rice", "quantity": "1 cup, cooked", "category": "grain"},
        ],
        "steps": [
            "Add chicken, tomatoes, garlic, ginger, garam masala, and turmeric to slow cooker.",
            "Cook on LOW 6-8 hours or HIGH 3-4 hours.",
            "Shred chicken with two forks.",
            "Stir in coconut cream, cook 15 more minutes.",
            "Serve over basmati rice with naan bread.",
            "Garnish with fresh cilantro.",
        ],
        "tags": ["high-protein", "slow-cooker", "indian", "dinner", "meal-prep"],
        "calories": 410, "protein_g": 42, "carbs_g": 38, "fat_g": 12, "fiber_g": 4, "sugar_g": 6,
        "servings": 4, "cook_time_minutes": 240, "difficulty": "easy",
        "views": 2100000, "likes": 156000, "comments": 5800, "shares": 38000,
    },
    {
        "title": "Protein Overnight French Toast Bake",
        "description": "Prep Saturday night, bake Sunday morning. Feeds the whole family with 30g protein per slice.",
        "creator_username": "ambitiouskitchen",
        "creator_display_name": "Monique | Ambitious Kitchen",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@ambitiouskitchen",
        "creator_avatar_url": None,
        "creator_follower_count": 450000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example27",
        "thumbnail_url": "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600",
        "ingredients": [
            {"name": "whole wheat bread", "quantity": "8 slices, cubed", "category": "grain"},
            {"name": "eggs", "quantity": "4 large", "category": "protein"},
            {"name": "egg whites", "quantity": "4", "category": "protein"},
            {"name": "vanilla protein powder", "quantity": "2 scoops", "category": "supplement"},
            {"name": "milk", "quantity": "1 cup", "category": "dairy"},
            {"name": "cinnamon", "quantity": "2 tsp", "category": "spice"},
            {"name": "vanilla extract", "quantity": "1 tsp", "category": "pantry"},
            {"name": "blueberries", "quantity": "1 cup", "category": "produce"},
        ],
        "steps": [
            "Grease a 9x13 baking dish. Arrange bread cubes in a single layer.",
            "Whisk eggs, egg whites, protein powder, milk, cinnamon, and vanilla.",
            "Pour egg mixture over bread, pressing down gently.",
            "Scatter blueberries on top.",
            "Cover and refrigerate overnight (or at least 2 hours).",
            "Bake at 350°F for 35-40 minutes until golden and set.",
        ],
        "tags": ["high-protein", "breakfast", "meal-prep", "brunch", "family"],
        "calories": 280, "protein_g": 30, "carbs_g": 28, "fat_g": 6, "fiber_g": 4, "sugar_g": 8,
        "servings": 8, "cook_time_minutes": 40, "difficulty": "easy",
        "views": 670000, "likes": 49000, "comments": 1800, "shares": 12000,
    },
    {
        "title": "Chickpea & Quinoa Power Bowl",
        "description": "Plant-based protein from chickpeas and quinoa. Filling, nutritious, and incredibly flavorful.",
        "creator_username": "fromthecomfort",
        "creator_display_name": "From the Comfort of My Bowl",
        "creator_platform": "reddit",
        "creator_profile_url": "https://reddit.com/u/fromthecomfort",
        "creator_avatar_url": None,
        "creator_follower_count": 14000,
        "platform": "reddit",
        "source_url": "https://reddit.com/r/veganrecipes/comments/example28",
        "thumbnail_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
        "ingredients": [
            {"name": "cooked quinoa", "quantity": "1 cup", "category": "grain"},
            {"name": "chickpeas", "quantity": "1 can, drained", "category": "pantry"},
            {"name": "roasted sweet potato", "quantity": "1 cup, cubed", "category": "produce"},
            {"name": "kale", "quantity": "2 cups, massaged", "category": "produce"},
            {"name": "tahini", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "lemon juice", "quantity": "2 tbsp", "category": "pantry"},
        ],
        "steps": [
            "Cook quinoa according to package directions.",
            "Roast chickpeas at 400°F with cumin and paprika for 20 min.",
            "Massage kale with a pinch of salt and lemon juice.",
            "Whisk tahini, lemon juice, and water for dressing.",
            "Assemble bowls: quinoa, kale, sweet potato, crispy chickpeas.",
            "Drizzle with tahini dressing and enjoy!",
        ],
        "tags": ["plant-based", "vegan", "high-fiber", "bowl", "meal-prep"],
        "calories": 420, "protein_g": 18, "carbs_g": 58, "fat_g": 14, "fiber_g": 12, "sugar_g": 8,
        "servings": 2, "cook_time_minutes": 30, "difficulty": "easy",
        "views": 340000, "likes": 27000, "comments": 900, "shares": 6800,
    },
    {
        "title": "Honey Garlic Glazed Chicken",
        "description": "Sweet, sticky, garlicky perfection. This glaze is dangerously addictive and the chicken is so juicy.",
        "creator_username": "damndelicious",
        "creator_display_name": "Chungah | Damn Delicious",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@damndelicious",
        "creator_avatar_url": None,
        "creator_follower_count": 890000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=example29",
        "thumbnail_url": "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600",
        "ingredients": [
            {"name": "chicken thighs", "quantity": "1.5 lbs", "category": "protein"},
            {"name": "honey", "quantity": "3 tbsp", "category": "pantry"},
            {"name": "soy sauce", "quantity": "3 tbsp", "category": "condiment"},
            {"name": "garlic", "quantity": "5 cloves, minced", "category": "produce"},
            {"name": "rice vinegar", "quantity": "1 tbsp", "category": "pantry"},
            {"name": "sesame seeds", "quantity": "1 tbsp", "category": "pantry"},
        ],
        "steps": [
            "Season chicken thighs with salt and pepper.",
            "Sear chicken skin-side down in a hot pan, 5 min until crispy.",
            "Flip and cook 3 more minutes.",
            "Mix honey, soy sauce, garlic, and rice vinegar.",
            "Pour sauce over chicken, simmer 5-7 min until thick and glossy.",
            "Garnish with sesame seeds and green onions.",
        ],
        "tags": ["high-protein", "asian", "dinner", "quick", "honey-garlic"],
        "calories": 355, "protein_g": 36, "carbs_g": 18, "fat_g": 14, "fiber_g": 0, "sugar_g": 14,
        "servings": 4, "cook_time_minutes": 20, "difficulty": "easy",
        "views": 3200000, "likes": 234000, "comments": 8400, "shares": 52000,
    },
]


async def seed():
    from src.db.tables import Base
    from src.db.engine import engine, async_session

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        for i, r in enumerate(EXTRA_RECIPES):
            now = datetime.utcnow()
            row = RecipeRow(
                id=str(uuid.uuid4()),
                title=r["title"],
                description=r.get("description"),
                creator_username=r["creator_username"],
                creator_display_name=r.get("creator_display_name"),
                creator_platform=r["creator_platform"],
                creator_profile_url=r.get("creator_profile_url"),
                creator_avatar_url=r.get("creator_avatar_url"),
                creator_follower_count=r.get("creator_follower_count"),
                platform=r["platform"],
                source_url=r["source_url"],
                thumbnail_url=r.get("thumbnail_url"),
                video_url=r.get("video_url"),
                ingredients=r["ingredients"],
                steps=r["steps"],
                tags=r.get("tags", []),
                calories=r.get("calories"),
                protein_g=r.get("protein_g"),
                carbs_g=r.get("carbs_g"),
                fat_g=r.get("fat_g"),
                fiber_g=r.get("fiber_g"),
                sugar_g=r.get("sugar_g"),
                servings=r.get("servings"),
                cook_time_minutes=r.get("cook_time_minutes"),
                difficulty=r.get("difficulty"),
                views=r.get("views"),
                likes=r.get("likes"),
                comments=r.get("comments"),
                shares=r.get("shares"),
                virality_score=random.randint(60, 95),
                scraped_at=now - timedelta(hours=random.randint(1, 72)),
                published_at=now - timedelta(days=random.randint(1, 90)),
            )
            session.add(row)

        await session.commit()
        print(f"✅ Seeded {len(EXTRA_RECIPES)} extra recipes")


if __name__ == "__main__":
    asyncio.run(seed())
