"""Seed the FitBites database with realistic recipe data for development."""
import asyncio
import uuid
from datetime import datetime, timedelta
import random

from src.db.engine import engine, async_session
from src.db.tables import Base, RecipeRow


SEED_RECIPES = [
    {
        "title": "3-Ingredient Protein Ice Cream",
        "description": "Creamy, thick protein ice cream that tastes like the real thing. Only 280 calories with 42g protein. Went viral with 2.3M views!",
        "creator_username": "broccyourbody",
        "creator_display_name": "Broccy | Healthy Recipes",
        "creator_platform": "tiktok",
        "creator_profile_url": "https://tiktok.com/@broccyourbody",
        "creator_avatar_url": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100",
        "creator_follower_count": 1200000,
        "platform": "tiktok",
        "source_url": "https://tiktok.com/@broccyourbody/video/7321456789",
        "thumbnail_url": "https://images.unsplash.com/photo-1488900128323-21503983a07e?w=600",
        "ingredients": [
            {"name": "frozen banana", "quantity": "2 medium", "category": "produce"},
            {"name": "chocolate protein powder", "quantity": "1 scoop (30g)", "category": "supplement"},
            {"name": "unsweetened almond milk", "quantity": "1/4 cup", "category": "dairy"},
        ],
        "steps": [
            "Freeze ripe bananas for at least 4 hours (overnight is best).",
            "Add frozen banana chunks, protein powder, and almond milk to a food processor.",
            "Blend for 2-3 minutes, scraping sides as needed, until thick and creamy.",
            "Serve immediately for soft-serve texture, or freeze 30 min for firmer ice cream.",
        ],
        "tags": ["high-protein", "dessert", "quick", "3-ingredients", "viral"],
        "calories": 280, "protein_g": 42, "carbs_g": 38, "fat_g": 4, "fiber_g": 5, "sugar_g": 22,
        "servings": 1, "cook_time_minutes": 5, "difficulty": "easy",
        "views": 2300000, "likes": 412000, "comments": 8900, "shares": 45000,
    },
    {
        "title": "Crunchy Baked Chicken Tenders (Air Fryer)",
        "description": "Better than Chick-fil-A with half the calories. Crispy outside, juicy inside. 340 cal, 48g protein per serving.",
        "creator_username": "mealprepmandy",
        "creator_display_name": "Mandy | Meal Prep Queen",
        "creator_platform": "instagram",
        "creator_profile_url": "https://instagram.com/mealprepmandy",
        "creator_avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
        "creator_follower_count": 890000,
        "platform": "instagram",
        "source_url": "https://instagram.com/p/C3xYzAbcDeF",
        "thumbnail_url": "https://images.unsplash.com/photo-1562967914-608f82629710?w=600",
        "ingredients": [
            {"name": "chicken breast", "quantity": "1 lb (450g)", "category": "protein"},
            {"name": "panko breadcrumbs", "quantity": "1 cup", "category": "pantry"},
            {"name": "egg whites", "quantity": "2 large", "category": "protein"},
            {"name": "garlic powder", "quantity": "1 tsp", "category": "spice"},
            {"name": "paprika", "quantity": "1 tsp", "category": "spice"},
            {"name": "salt", "quantity": "1/2 tsp", "category": "spice"},
        ],
        "steps": [
            "Cut chicken breast into 1-inch wide strips.",
            "Season panko with garlic powder, paprika, and salt in a shallow bowl.",
            "Whisk egg whites in another shallow bowl.",
            "Dip chicken in egg whites, then coat in seasoned panko, pressing to adhere.",
            "Air fry at 400°F (200°C) for 10-12 minutes, flipping halfway, until golden and cooked through.",
            "Serve with honey mustard or sugar-free ketchup.",
        ],
        "tags": ["high-protein", "meal-prep", "air-fryer", "chicken", "low-fat"],
        "calories": 340, "protein_g": 48, "carbs_g": 22, "fat_g": 6, "fiber_g": 1, "sugar_g": 1,
        "servings": 2, "cook_time_minutes": 15, "difficulty": "easy",
        "views": 1800000, "likes": 267000, "comments": 5400, "shares": 38000,
    },
    {
        "title": "Overnight Protein Oats (5 Ways)",
        "description": "Prep once, eat all week. Each jar is 380 cal with 35g protein. The cookie dough flavor is INSANE.",
        "creator_username": "thefitfoodie",
        "creator_display_name": "The Fit Foodie",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@thefitfoodie",
        "creator_avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
        "creator_follower_count": 2100000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=dQw4w9WgXcQ_oats",
        "thumbnail_url": "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600",
        "ingredients": [
            {"name": "rolled oats", "quantity": "1/2 cup", "category": "grain"},
            {"name": "vanilla protein powder", "quantity": "1 scoop (30g)", "category": "supplement"},
            {"name": "Greek yogurt (0% fat)", "quantity": "1/2 cup", "category": "dairy"},
            {"name": "unsweetened almond milk", "quantity": "1/2 cup", "category": "dairy"},
            {"name": "chia seeds", "quantity": "1 tbsp", "category": "seed"},
            {"name": "honey", "quantity": "1 tsp", "category": "sweetener"},
        ],
        "steps": [
            "Combine oats, protein powder, chia seeds in a mason jar or container.",
            "Add Greek yogurt, almond milk, and honey. Stir well to combine.",
            "Seal and refrigerate overnight (at least 6 hours).",
            "In the morning, stir and add toppings: berries, banana, nuts, or chocolate chips.",
            "Can be stored in fridge for up to 5 days.",
        ],
        "tags": ["high-protein", "meal-prep", "breakfast", "overnight-oats", "easy"],
        "calories": 380, "protein_g": 35, "carbs_g": 42, "fat_g": 8, "fiber_g": 7, "sugar_g": 12,
        "servings": 1, "cook_time_minutes": 5, "difficulty": "easy",
        "views": 4500000, "likes": 890000, "comments": 12000, "shares": 67000,
    },
    {
        "title": "Spicy Salmon Rice Bowl",
        "description": "The viral TikTok salmon rice bowl but macro-friendly. 420 cal, 38g protein. Restaurant quality at home.",
        "creator_username": "emilymariko",
        "creator_display_name": "Emily Mariko",
        "creator_platform": "tiktok",
        "creator_profile_url": "https://tiktok.com/@emilymariko",
        "creator_avatar_url": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
        "creator_follower_count": 12500000,
        "platform": "tiktok",
        "source_url": "https://tiktok.com/@emilymariko/video/7299876543",
        "thumbnail_url": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
        "ingredients": [
            {"name": "salmon fillet", "quantity": "6 oz (170g)", "category": "protein"},
            {"name": "sushi rice", "quantity": "3/4 cup cooked", "category": "grain"},
            {"name": "sriracha", "quantity": "1 tbsp", "category": "sauce"},
            {"name": "soy sauce (low sodium)", "quantity": "1 tbsp", "category": "sauce"},
            {"name": "rice vinegar", "quantity": "1 tsp", "category": "sauce"},
            {"name": "avocado", "quantity": "1/4 medium", "category": "produce"},
            {"name": "nori sheets", "quantity": "1 sheet, crumbled", "category": "pantry"},
            {"name": "sesame seeds", "quantity": "1 tsp", "category": "seed"},
        ],
        "steps": [
            "Season salmon with salt and pepper. Bake at 400°F for 12-15 minutes or until flaky.",
            "While salmon bakes, cook sushi rice according to package directions. Season with rice vinegar.",
            "Flake cooked salmon into chunks with a fork.",
            "Mix sriracha and soy sauce for the spicy sauce.",
            "Assemble bowl: rice base, flaked salmon on top.",
            "Drizzle with spicy sauce, add sliced avocado, crumbled nori, and sesame seeds.",
        ],
        "tags": ["high-protein", "salmon", "rice-bowl", "viral", "asian-inspired"],
        "calories": 420, "protein_g": 38, "carbs_g": 35, "fat_g": 14, "fiber_g": 3, "sugar_g": 2,
        "servings": 1, "cook_time_minutes": 20, "difficulty": "easy",
        "views": 89000000, "likes": 12000000, "comments": 230000, "shares": 3400000,
    },
    {
        "title": "Cottage Cheese Flatbread (High Protein Pizza)",
        "description": "2-ingredient flatbread dough that's basically all protein. Top however you want. 310 cal, 32g protein for the whole thing.",
        "creator_username": "fithealthyrecipes",
        "creator_display_name": "Fit Healthy Recipes",
        "creator_platform": "instagram",
        "creator_profile_url": "https://instagram.com/fithealthyrecipes",
        "creator_avatar_url": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
        "creator_follower_count": 560000,
        "platform": "instagram",
        "source_url": "https://instagram.com/p/C4aBcDeFgHi",
        "thumbnail_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600",
        "ingredients": [
            {"name": "cottage cheese", "quantity": "1 cup", "category": "dairy"},
            {"name": "self-rising flour", "quantity": "1/2 cup", "category": "pantry"},
            {"name": "marinara sauce", "quantity": "2 tbsp", "category": "sauce"},
            {"name": "mozzarella (part-skim)", "quantity": "1/4 cup shredded", "category": "dairy"},
            {"name": "fresh basil", "quantity": "4-5 leaves", "category": "produce"},
        ],
        "steps": [
            "Blend cottage cheese in food processor until completely smooth (no lumps).",
            "Add self-rising flour and pulse until dough forms a ball.",
            "Roll dough out on floured surface to 1/4 inch thickness.",
            "Transfer to a parchment-lined baking sheet.",
            "Spread marinara, top with mozzarella.",
            "Bake at 425°F (220°C) for 12-15 minutes until edges are golden and cheese is bubbly.",
            "Top with fresh basil. Slice and serve.",
        ],
        "tags": ["high-protein", "pizza", "cottage-cheese", "viral", "low-calorie"],
        "calories": 310, "protein_g": 32, "carbs_g": 30, "fat_g": 8, "fiber_g": 2, "sugar_g": 5,
        "servings": 1, "cook_time_minutes": 20, "difficulty": "easy",
        "views": 5600000, "likes": 780000, "comments": 14000, "shares": 92000,
    },
    {
        "title": "Greek Yogurt Protein Bark",
        "description": "Frozen yogurt bark that's basically candy but healthy. 160 cal, 18g protein. Perfect sweet tooth fix.",
        "creator_username": "cleanfoodcrush",
        "creator_display_name": "Clean Food Crush",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@cleanfoodcrush",
        "creator_avatar_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
        "creator_follower_count": 980000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=yogurt_bark_123",
        "thumbnail_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
        "ingredients": [
            {"name": "Greek yogurt (0% fat)", "quantity": "2 cups", "category": "dairy"},
            {"name": "honey", "quantity": "2 tbsp", "category": "sweetener"},
            {"name": "vanilla extract", "quantity": "1 tsp", "category": "pantry"},
            {"name": "mixed berries", "quantity": "1/2 cup", "category": "produce"},
            {"name": "dark chocolate chips", "quantity": "2 tbsp", "category": "pantry"},
            {"name": "granola", "quantity": "1/4 cup", "category": "grain"},
        ],
        "steps": [
            "Line a baking sheet with parchment paper.",
            "Mix Greek yogurt with honey and vanilla extract until smooth.",
            "Spread yogurt mixture evenly on parchment, about 1/4 inch thick.",
            "Scatter berries, chocolate chips, and granola on top. Press gently.",
            "Freeze for at least 3 hours until completely solid.",
            "Break into pieces and store in freezer bag. Keeps for 2 weeks.",
        ],
        "tags": ["high-protein", "dessert", "snack", "frozen", "easy", "no-bake"],
        "calories": 160, "protein_g": 18, "carbs_g": 20, "fat_g": 3, "fiber_g": 2, "sugar_g": 16,
        "servings": 4, "cook_time_minutes": 10, "difficulty": "easy",
        "views": 3200000, "likes": 540000, "comments": 7800, "shares": 51000,
    },
    {
        "title": "Anabolic French Toast",
        "description": "Bodybuilder French toast that actually tastes amazing. 450 cal, 52g protein. Weekend breakfast staple.",
        "creator_username": "gregdoucette",
        "creator_display_name": "Greg Doucette",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@gregdoucette",
        "creator_avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
        "creator_follower_count": 4800000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=anabolic_french_toast",
        "thumbnail_url": "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600",
        "ingredients": [
            {"name": "egg whites", "quantity": "1 cup (8 whites)", "category": "protein"},
            {"name": "whole egg", "quantity": "1 large", "category": "protein"},
            {"name": "vanilla protein powder", "quantity": "1 scoop (30g)", "category": "supplement"},
            {"name": "cinnamon", "quantity": "1 tsp", "category": "spice"},
            {"name": "light bread", "quantity": "4 slices", "category": "grain"},
            {"name": "sugar-free syrup", "quantity": "2 tbsp", "category": "sweetener"},
            {"name": "mixed berries", "quantity": "1/2 cup", "category": "produce"},
        ],
        "steps": [
            "Whisk egg whites, whole egg, protein powder, and cinnamon until smooth.",
            "Dip each bread slice in egg mixture, letting it soak for 10 seconds per side.",
            "Cook on a non-stick pan over medium heat, 2-3 minutes per side until golden.",
            "Stack on plate, top with berries and sugar-free syrup.",
            "Optional: add a dollop of Greek yogurt for extra protein.",
        ],
        "tags": ["high-protein", "breakfast", "anabolic", "bodybuilding", "french-toast"],
        "calories": 450, "protein_g": 52, "carbs_g": 40, "fat_g": 8, "fiber_g": 4, "sugar_g": 8,
        "servings": 1, "cook_time_minutes": 15, "difficulty": "easy",
        "views": 8700000, "likes": 1200000, "comments": 28000, "shares": 120000,
    },
    {
        "title": "Creamy Tuscan Chicken Skillet",
        "description": "One-pan creamy chicken that's secretly healthy. 380 cal, 42g protein. Date night approved.",
        "creator_username": "joshuaweissman",
        "creator_display_name": "Joshua Weissman",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@joshuaweissman",
        "creator_avatar_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
        "creator_follower_count": 9200000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=tuscan_chicken_456",
        "thumbnail_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600",
        "ingredients": [
            {"name": "chicken breast", "quantity": "2 large (1 lb)", "category": "protein"},
            {"name": "sun-dried tomatoes", "quantity": "1/3 cup", "category": "produce"},
            {"name": "fresh spinach", "quantity": "2 cups", "category": "produce"},
            {"name": "garlic", "quantity": "4 cloves, minced", "category": "produce"},
            {"name": "light cream cheese", "quantity": "2 oz", "category": "dairy"},
            {"name": "chicken broth", "quantity": "1/2 cup", "category": "pantry"},
            {"name": "Italian seasoning", "quantity": "1 tbsp", "category": "spice"},
            {"name": "parmesan cheese", "quantity": "2 tbsp grated", "category": "dairy"},
        ],
        "steps": [
            "Season chicken with Italian seasoning, salt, and pepper.",
            "Sear chicken in a hot skillet with cooking spray, 5-6 min per side. Remove and set aside.",
            "In same pan, sauté garlic for 30 seconds until fragrant.",
            "Add sun-dried tomatoes, chicken broth, and cream cheese. Stir until creamy.",
            "Add spinach and stir until wilted.",
            "Return chicken to pan, spoon sauce over top.",
            "Simmer 2-3 minutes. Top with parmesan and serve.",
        ],
        "tags": ["high-protein", "dinner", "one-pan", "chicken", "creamy", "date-night"],
        "calories": 380, "protein_g": 42, "carbs_g": 12, "fat_g": 16, "fiber_g": 3, "sugar_g": 4,
        "servings": 2, "cook_time_minutes": 25, "difficulty": "medium",
        "views": 12000000, "likes": 1800000, "comments": 42000, "shares": 280000,
    },
    {
        "title": "Protein Cookie Dough Bites",
        "description": "Taste exactly like cookie dough, 100 cal each with 12g protein. Meal prep these on Sunday!",
        "creator_username": "macrofriendlyfood",
        "creator_display_name": "Macro Friendly Food",
        "creator_platform": "tiktok",
        "creator_profile_url": "https://tiktok.com/@macrofriendlyfood",
        "creator_avatar_url": "https://images.unsplash.com/photo-1599566150163-29194dcabd9c?w=100",
        "creator_follower_count": 720000,
        "platform": "tiktok",
        "source_url": "https://tiktok.com/@macrofriendlyfood/video/7345678901",
        "thumbnail_url": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600",
        "ingredients": [
            {"name": "chickpeas (drained)", "quantity": "1 can (15 oz)", "category": "protein"},
            {"name": "vanilla protein powder", "quantity": "1 scoop (30g)", "category": "supplement"},
            {"name": "peanut butter", "quantity": "2 tbsp", "category": "nut-butter"},
            {"name": "maple syrup", "quantity": "2 tbsp", "category": "sweetener"},
            {"name": "vanilla extract", "quantity": "1 tsp", "category": "pantry"},
            {"name": "mini chocolate chips", "quantity": "2 tbsp", "category": "pantry"},
        ],
        "steps": [
            "Drain and rinse chickpeas. Pat dry with paper towel.",
            "Add chickpeas, protein powder, peanut butter, maple syrup, and vanilla to food processor.",
            "Blend until completely smooth, scraping sides as needed (about 2 minutes).",
            "Fold in mini chocolate chips by hand.",
            "Roll into 12 balls (about 1 tbsp each).",
            "Refrigerate for at least 1 hour. Store in fridge for up to 1 week.",
        ],
        "tags": ["high-protein", "snack", "meal-prep", "no-bake", "dessert", "cookie-dough"],
        "calories": 100, "protein_g": 12, "carbs_g": 10, "fat_g": 4, "fiber_g": 2, "sugar_g": 5,
        "servings": 12, "cook_time_minutes": 10, "difficulty": "easy",
        "views": 6800000, "likes": 920000, "comments": 16000, "shares": 78000,
    },
    {
        "title": "Egg White Wrap Hack",
        "description": "Use egg whites as a wrap — 0 carbs, all protein. Fill with anything. 220 cal, 35g protein.",
        "creator_username": "willtennyson",
        "creator_display_name": "Will Tennyson",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@willtennyson",
        "creator_avatar_url": "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100",
        "creator_follower_count": 3400000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=egg_white_wrap_789",
        "thumbnail_url": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600",
        "ingredients": [
            {"name": "egg whites", "quantity": "1 cup (8 whites)", "category": "protein"},
            {"name": "turkey breast (deli)", "quantity": "4 oz", "category": "protein"},
            {"name": "avocado", "quantity": "1/4 medium", "category": "produce"},
            {"name": "spinach", "quantity": "handful", "category": "produce"},
            {"name": "hot sauce", "quantity": "to taste", "category": "sauce"},
        ],
        "steps": [
            "Pour egg whites into a large non-stick pan over medium-low heat.",
            "Tilt pan to spread egg whites into a thin, even circle (like a crepe).",
            "Cook for 3-4 minutes until set on top — do NOT flip.",
            "Slide egg white 'wrap' onto a plate.",
            "Layer turkey, avocado, spinach, and hot sauce down the center.",
            "Roll up like a burrito. Cut in half and serve.",
        ],
        "tags": ["high-protein", "low-carb", "keto", "wrap", "lunch", "quick"],
        "calories": 220, "protein_g": 35, "carbs_g": 4, "fat_g": 8, "fiber_g": 2, "sugar_g": 1,
        "servings": 1, "cook_time_minutes": 10, "difficulty": "easy",
        "views": 7200000, "likes": 980000, "comments": 19000, "shares": 95000,
    },
    {
        "title": "High Protein Ramen (Healthy Version)",
        "description": "Cozy ramen bowl with 45g protein and only 390 cal. Better than takeout, ready in 20 min.",
        "creator_username": "pickuplimes",
        "creator_display_name": "Pick Up Limes",
        "creator_platform": "youtube",
        "creator_profile_url": "https://youtube.com/@pickuplimes",
        "creator_avatar_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100",
        "creator_follower_count": 4200000,
        "platform": "youtube",
        "source_url": "https://youtube.com/watch?v=protein_ramen_101",
        "thumbnail_url": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600",
        "ingredients": [
            {"name": "ramen noodles", "quantity": "1 pack", "category": "grain"},
            {"name": "chicken breast", "quantity": "6 oz (170g)", "category": "protein"},
            {"name": "soft-boiled egg", "quantity": "1 large", "category": "protein"},
            {"name": "low-sodium chicken broth", "quantity": "2 cups", "category": "pantry"},
            {"name": "soy sauce", "quantity": "1 tbsp", "category": "sauce"},
            {"name": "ginger", "quantity": "1 tsp grated", "category": "produce"},
            {"name": "garlic", "quantity": "2 cloves", "category": "produce"},
            {"name": "green onions", "quantity": "2 stalks", "category": "produce"},
            {"name": "sesame oil", "quantity": "1/2 tsp", "category": "oil"},
        ],
        "steps": [
            "Slice chicken breast thin. Season with salt and pepper.",
            "Sauté ginger and garlic in sesame oil for 30 seconds.",
            "Add chicken broth and soy sauce. Bring to a boil.",
            "Add chicken slices, cook 3-4 minutes until done.",
            "Cook ramen noodles in the broth for 2-3 minutes.",
            "While broth simmers, soft-boil an egg (6.5 min in boiling water, then ice bath).",
            "Serve in a deep bowl. Top with halved egg, green onions, and optional chili oil.",
        ],
        "tags": ["high-protein", "dinner", "ramen", "asian-inspired", "comfort-food", "soup"],
        "calories": 390, "protein_g": 45, "carbs_g": 32, "fat_g": 10, "fiber_g": 2, "sugar_g": 3,
        "servings": 1, "cook_time_minutes": 20, "difficulty": "medium",
        "views": 5100000, "likes": 720000, "comments": 11000, "shares": 63000,
    },
    {
        "title": "Chocolate Protein Mug Cake (2 Minutes)",
        "description": "Warm, fudgy chocolate cake in a mug. 210 cal, 28g protein. Microwave in 90 seconds flat.",
        "creator_username": "lowcalrecipes",
        "creator_display_name": "Low Cal Recipes",
        "creator_platform": "tiktok",
        "creator_profile_url": "https://tiktok.com/@lowcalrecipes",
        "creator_avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
        "creator_follower_count": 1500000,
        "platform": "tiktok",
        "source_url": "https://tiktok.com/@lowcalrecipes/video/7356789012",
        "thumbnail_url": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600",
        "ingredients": [
            {"name": "chocolate protein powder", "quantity": "1 scoop (30g)", "category": "supplement"},
            {"name": "cocoa powder", "quantity": "1 tbsp", "category": "pantry"},
            {"name": "baking powder", "quantity": "1/4 tsp", "category": "pantry"},
            {"name": "egg white", "quantity": "1 large", "category": "protein"},
            {"name": "unsweetened almond milk", "quantity": "3 tbsp", "category": "dairy"},
            {"name": "vanilla extract", "quantity": "1/2 tsp", "category": "pantry"},
        ],
        "steps": [
            "Mix protein powder, cocoa powder, and baking powder in a microwave-safe mug.",
            "Add egg white, almond milk, and vanilla extract. Stir until smooth (no lumps!).",
            "Microwave on high for 60-90 seconds. Watch carefully — it rises then settles.",
            "Let cool 1 minute. Top with a drizzle of peanut butter or sugar-free whipped cream.",
        ],
        "tags": ["high-protein", "dessert", "quick", "mug-cake", "chocolate", "low-calorie"],
        "calories": 210, "protein_g": 28, "carbs_g": 12, "fat_g": 4, "fiber_g": 3, "sugar_g": 2,
        "servings": 1, "cook_time_minutes": 2, "difficulty": "easy",
        "views": 9400000, "likes": 1400000, "comments": 32000, "shares": 140000,
    },
]


import math

def compute_virality(r):
    views = r.get("views", 0)
    likes = r.get("likes", 0)
    comments = r.get("comments", 0)
    shares = r.get("shares", 0)
    v = min(math.log10(max(views, 1)) / 7 * 40, 40)
    l = min(math.log10(max(likes, 1)) / 6 * 30, 30)
    c = min(math.log10(max(comments, 1)) / 5 * 20, 20)
    s = min(math.log10(max(shares, 1)) / 5 * 10, 10)
    return round(v + l + c + s, 1)


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        for r in SEED_RECIPES:
            row = RecipeRow(
                id=str(uuid.uuid4()),
                title=r["title"],
                description=r["description"],
                creator_username=r["creator_username"],
                creator_display_name=r["creator_display_name"],
                creator_platform=r["creator_platform"],
                creator_profile_url=r["creator_profile_url"],
                creator_avatar_url=r.get("creator_avatar_url"),
                creator_follower_count=r.get("creator_follower_count"),
                platform=r["platform"],
                source_url=r["source_url"],
                thumbnail_url=r.get("thumbnail_url"),
                ingredients=r["ingredients"],
                steps=r["steps"],
                tags=r["tags"],
                calories=r.get("calories"),
                protein_g=r.get("protein_g"),
                carbs_g=r.get("carbs_g"),
                fat_g=r.get("fat_g"),
                fiber_g=r.get("fiber_g"),
                sugar_g=r.get("sugar_g"),
                servings=r.get("servings", 1),
                cook_time_minutes=r.get("cook_time_minutes"),
                difficulty=r.get("difficulty"),
                views=r.get("views"),
                likes=r.get("likes"),
                comments=r.get("comments"),
                shares=r.get("shares"),
                virality_score=compute_virality(r),
                published_at=datetime.now() - timedelta(days=random.randint(1, 30)),
            )
            session.add(row)
        await session.commit()
        print(f"✅ Seeded {len(SEED_RECIPES)} recipes")


if __name__ == "__main__":
    asyncio.run(seed())
