"""Tests for the FitBites analytics data pipeline and dashboard generation.

Covers:
- Data seeding correctness
- Metric computation accuracy
- Funnel math validation
- Dashboard HTML generation
- Revenue estimation logic
"""
import asyncio
import json
import os
import sys
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class TestRevenueEstimation:
    """Test revenue calculation logic."""

    def test_amazon_cps_revenue(self):
        from src.analytics.revenue import _estimate_revenue
        # Amazon grocery: 1% of $35 AOV = $0.35 per conversion
        rev = _estimate_revenue("amazon", 10, "grocery")
        assert rev == pytest.approx(3.5, abs=0.01)

    def test_amazon_kitchen_revenue(self):
        from src.analytics.revenue import _estimate_revenue
        # Kitchen: 3% of $35 = $1.05 per conversion
        rev = _estimate_revenue("amazon", 10, "kitchen")
        assert rev == pytest.approx(10.5, abs=0.01)

    def test_instacart_cpa_revenue(self):
        from src.analytics.revenue import _estimate_revenue
        # Instacart: $5 CPA
        rev = _estimate_revenue("instacart", 10)
        assert rev == pytest.approx(50.0, abs=0.01)

    def test_unknown_provider_defaults_to_amazon(self):
        from src.analytics.revenue import _estimate_revenue
        rev = _estimate_revenue("unknown_provider", 5)
        # Should use amazon default: 2% of $35 = $0.70 per conversion
        assert rev == pytest.approx(3.5, abs=0.01)


class TestHealthScoring:
    """Test financial health scoring logic."""

    def test_health_grade_boundaries(self):
        from src.analytics.revenue import _health_grade
        assert _health_grade(95) == "A"
        assert _health_grade(90) == "A"
        assert _health_grade(89) == "B"
        assert _health_grade(75) == "B"
        assert _health_grade(60) == "C"
        assert _health_grade(40) == "D"
        assert _health_grade(39) == "F"
        assert _health_grade(0) == "F"

    def test_metric_status_higher_is_better(self):
        from src.analytics.revenue import _metric_status
        assert _metric_status(1.0, 1.0) == "green"
        assert _metric_status(2.0, 1.0) == "green"
        assert _metric_status(0.7, 1.0) == "yellow"
        assert _metric_status(0.3, 1.0) == "red"

    def test_metric_status_lower_is_better(self):
        from src.analytics.revenue import _metric_status
        assert _metric_status(0.5, 1.0, higher_is_better=False) == "green"
        assert _metric_status(1.3, 1.0, higher_is_better=False) == "yellow"
        assert _metric_status(2.0, 1.0, higher_is_better=False) == "red"


class TestDashboardGeneration:
    """Test that the dashboard generator produces valid output."""

    def test_dashboard_html_exists_after_seed(self):
        """Verify dashboard.html was generated by the seed+generate pipeline."""
        path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "static", "dashboard.html"
        )
        assert os.path.exists(path), "dashboard.html should exist after generate_dashboard.py"
        
        with open(path) as f:
            html = f.read()
        
        # Basic structure checks
        assert "<!DOCTYPE html>" in html
        assert "FitBites Analytics" in html
        assert "Chart.js" in html or "chart.js" in html
        assert "dauChart" in html
        assert "platformChart" in html
        assert "recipesChart" in html
        assert "revenueChart" in html

    def test_metrics_json_valid(self):
        """Verify metrics.json is valid and contains expected keys."""
        path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "static", "metrics.json"
        )
        assert os.path.exists(path)
        
        with open(path) as f:
            data = json.load(f)
        
        required_keys = [
            "dau", "wau", "mau", "total_events_30d",
            "dau_trend", "event_counts", "funnel",
            "platforms", "top_recipes", "affiliate_clicks",
            "revenue_by_partner", "total_revenue_est",
            "retention", "arpu", "affiliate_ctr",
        ]
        for key in required_keys:
            assert key in data, f"Missing key: {key}"
        
        # Sanity checks
        assert data["mau"] > 0
        assert data["dau"] > 0
        assert data["dau"] <= data["wau"] <= data["mau"]
        assert len(data["dau_trend"]) > 0
        assert data["funnel"]["app_open"] > 0
        assert data["funnel"]["recipe_view"] > 0
        assert data["total_revenue_est"] >= 0

    def test_funnel_conversion_stages_decrease(self):
        """Conversion-intent stages should decrease: save > click > conversion.
        Note: recipe_view can exceed app_open since users view multiple recipes per session.
        """
        path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "static", "metrics.json"
        )
        with open(path) as f:
            data = json.load(f)
        
        funnel = data["funnel"]
        # These should always decrease (conversion intent stages)
        assert funnel["recipe_save"] <= funnel["recipe_view"]
        assert funnel["affiliate_click"] <= funnel["recipe_view"]
        assert funnel["affiliate_conversion"] <= funnel["affiliate_click"]

    def test_retention_rate_bounds(self):
        """Retention rate should be between 0 and 100."""
        path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "static", "metrics.json"
        )
        with open(path) as f:
            data = json.load(f)
        
        rate = data["retention"]["rate"]
        assert 0 <= rate <= 100


class TestCommissionRates:
    """Verify commission rate data integrity."""

    def test_all_providers_have_rates(self):
        from src.analytics.revenue import COMMISSION_RATES
        expected = ["amazon", "iherb", "instacart", "thrive", "hellofresh", "factor"]
        for p in expected:
            assert p in COMMISSION_RATES, f"Missing provider: {p}"

    def test_all_providers_have_default(self):
        from src.analytics.revenue import COMMISSION_RATES
        for provider, rates in COMMISSION_RATES.items():
            assert "default" in rates or "cpa" in rates, \
                f"Provider {provider} needs 'default' or 'cpa' rate"
