"""initial_schema

Revision ID: 162747af30a6
Revises: 
Create Date: 2026-02-24 19:42:09.580041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162747af30a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event'), 'analytics_events', ['event'], unique=False)
    op.create_index(op.f('ix_analytics_events_timestamp'), 'analytics_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index('ix_events_event_ts', 'analytics_events', ['event', 'timestamp'], unique=False)
    op.create_index('ix_events_user_ts', 'analytics_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_username', sa.String(length=200), nullable=False),
    sa.Column('creator_display_name', sa.String(length=200), nullable=True),
    sa.Column('creator_platform', sa.Enum('TIKTOK', 'INSTAGRAM', 'YOUTUBE', 'REDDIT', name='platform'), nullable=False),
    sa.Column('creator_profile_url', sa.String(length=1000), nullable=False),
    sa.Column('creator_avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('creator_follower_count', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('TIKTOK', 'INSTAGRAM', 'YOUTUBE', 'REDDIT', name='platform'), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('video_url', sa.String(length=2000), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('ix_recipes_calories', 'recipes', ['calories'], unique=False)
    op.create_index(op.f('ix_recipes_platform'), 'recipes', ['platform'], unique=False)
    op.create_index('ix_recipes_protein', 'recipes', ['protein_g'], unique=False)
    op.create_index(op.f('ix_recipes_title'), 'recipes', ['title'], unique=False)
    op.create_index(op.f('ix_recipes_virality_score'), 'recipes', ['virality_score'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_hash', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reqlog_path_ts', 'request_logs', ['path', 'timestamp'], unique=False)
    op.create_index(op.f('ix_request_logs_path'), 'request_logs', ['path'], unique=False)
    op.create_index(op.f('ix_request_logs_timestamp'), 'request_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=2000), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('grocery_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_lists_user_id'), 'grocery_lists', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('daily_protein_g', sa.Float(), nullable=True),
    sa.Column('daily_carbs_g', sa.Float(), nullable=True),
    sa.Column('daily_fat_g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_plans_user_dates', 'meal_plans', ['user_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('saved_recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('collection', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_recipe')
    )
    op.create_index(op.f('ix_saved_recipes_recipe_id'), 'saved_recipes', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_saved_recipes_user_id'), 'saved_recipes', ['user_id'], unique=False)
    op.create_index('ix_saved_user_collection', 'saved_recipes', ['user_id', 'collection'], unique=False)
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=True),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('servings', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day_index', 'meal_type', 'recipe_id', name='uq_plan_slot_recipe')
    )
    op.create_index('ix_entries_plan_day', 'meal_plan_entries', ['plan_id', 'day_index'], unique=False)
    op.create_index(op.f('ix_meal_plan_entries_plan_id'), 'meal_plan_entries', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plan_entries_plan_id'), table_name='meal_plan_entries')
    op.drop_index('ix_entries_plan_day', table_name='meal_plan_entries')
    op.drop_table('meal_plan_entries')
    op.drop_index('ix_saved_user_collection', table_name='saved_recipes')
    op.drop_index(op.f('ix_saved_recipes_user_id'), table_name='saved_recipes')
    op.drop_index(op.f('ix_saved_recipes_recipe_id'), table_name='saved_recipes')
    op.drop_table('saved_recipes')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index('ix_meal_plans_user_dates', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_grocery_lists_user_id'), table_name='grocery_lists')
    op.drop_table('grocery_lists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_request_logs_timestamp'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_path'), table_name='request_logs')
    op.drop_index('ix_reqlog_path_ts', table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_recipes_virality_score'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_title'), table_name='recipes')
    op.drop_index('ix_recipes_protein', table_name='recipes')
    op.drop_index(op.f('ix_recipes_platform'), table_name='recipes')
    op.drop_index('ix_recipes_calories', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('ix_events_user_ts', table_name='analytics_events')
    op.drop_index('ix_events_event_ts', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_timestamp'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
