#!/bin/bash
# Generate secure production secrets for FitBites backend
# Usage: ./scripts/generate-secrets.sh > .env.production

set -e

echo "# FitBites Production Secrets"
echo "# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
echo "# KEEP THIS FILE SECURE - DO NOT COMMIT"
echo ""

echo "# JWT Secret (64 random bytes, hex-encoded)"
JWT_SECRET=$(openssl rand -hex 64)
echo "JWT_SECRET=$JWT_SECRET"
echo ""

echo "# Affiliate Signing Key (64 random bytes, hex-encoded)"
AFFILIATE_KEY=$(openssl rand -hex 64)
echo "AFFILIATE_SIGNING_KEY=$AFFILIATE_KEY"
echo ""

echo "# PostgreSQL Password (32 random bytes, base64)"
PG_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
echo "POSTGRES_PASSWORD=$PG_PASSWORD"
echo ""

echo "# Add these to your Railway environment variables:"
echo "# 1. Go to https://railway.app/dashboard"
echo "# 2. Select your FitBites project"
echo "# 3. Go to Variables tab"
echo "# 4. Add each variable above (JWT_SECRET, AFFILIATE_SIGNING_KEY, POSTGRES_PASSWORD)"
echo ""
echo "# Database URL will be auto-generated by Railway (don't set manually)"
